title: Vocal Harmonizer
description: Vocal Harmonizer created using Max as final project for MUMT 307 Music and Audio Computing 2, Winter 2018

## Index 

1.  [Introduction](./introduction.md)
1.  [The Interface](./interface.md)
1.  [Pre-processing](./preprocessing.md)
1.  [Pitch-Shifting](./pitchshifting.md)
1.  [Formant Analysis](./formantanalysis.md)
1.  [Effects](./effects.md)
1.  [Limitations and Outlook](./limitations)
1.  [References](./references.md)

theme: jekyll-theme-dinky


