title: Vocal Harmonizer
description: Vocal Harmonizer created using Max as final project for MUMT 307 Music and Audio Computing 2, Winter 2018

## Index 

-  [Introduction](./introduction.md)
-  [The Interface](./interface.md)
-  [Pre-processing](./preprocessing.md)
-  [Pitch-Shifting](./pitchshifting.md)
-  [Formant Analysis](./formantanalysis.md)
-  [Effects](./effects.md)
-  [Limitations and Outlook](./limitations)
-  [References](./references.md)

theme: jekyll-theme-dinky


