title: Vocal Harmonizer
description: 



-  [Introduction](./introduction.md)
-  [The Interface](./interface.md)
-  [Pre-processing](./preprocessing.md)
-  [Pitch-Shifting](./pitchshifting.md)
-  [Formant Analysis](./formantanalysis.md)
-  [Effects](./effects.md)
-  [Limitations and Outlook](./limitations)
-  [References](./references.md)

theme: jekyll-theme-dinky


